### ISSUE TITLE
Setting up OpenID connect / OIDC

### ISSUE THREAD

**Issue by reteps** [techservicesillinois/shib-in-a-box#5]
Looking for URLs / documentation for setting up OpenID connect on the Illinois Shibboleth Service Provider.

**Comment by kwessel** [comment]
The Shibboleth service provider doesn't support OIDC. The service provider is the piece you run on the same server as your application, and it speaks SAML. If you want to use OIDC, you would use one of the many available OIDC client libraries in your application or, on Apache, possibly use apache's mod_auth_openidc. If you want to interface it with the Urbana Shibboleth identity provider, please contact shibboleth-mgr@illinois.edu. While we have some mainstream apps using OIDC, they are still few, and the documentation doesn't exist yet for setting it up.

**Comment by kwessel** [comment]
No, you don't self-host the authentication server. Shibboleth does that. But getting support from a production service through a Github issue isn't a good way for us to track this item. Sorry if that wsn't clear.

**Comment by reteps** [comment]
Sorry, I meant to say I still have to host the Service Provider. I am switching to that email for future communications.
